export type DocumentListItem = {
  id: number;
  requestorName: string;
  buFu: string;
  extension: string;
  submitDate?: Date;
  approvalDate?: Date;
  urgency: string;
  documentType: string;
  documentTitle: string;
  documentDescription: string;
  documentNumber: string;
  documentUrl?: string;
  documentStatus?: string;
  documentStage?: string;
};

export const documentList: DocumentListItem[] = [
  {
    id: 0,
    requestorName: "John Doe",
    buFu: "Finance",
    extension: "1234",
    submitDate: new Date("2025-01-15"),
    approvalDate: undefined,
    urgency: "High",
    documentType: "Invoice",
    documentTitle: "Document 0001",
    documentDescription: "Monthly invoice for January 2025",
    documentNumber: "DOC-2025-0001",
    documentUrl: "",
    documentStatus: "Pending",
    documentStage: "Submitted",
  },
  {
    id: 1,
    requestorName: "Jane Smith",
    buFu: "HR",
    extension: "5678",
    submitDate: new Date("2025-01-14"),
    approvalDate: new Date("2025-01-16"),
    urgency: "Medium",
    documentType: "Contract",
    documentUrl: "",
    documentTitle: "Document 0002",
    documentDescription: "Employment contract for new hire",
    documentNumber: "DOC-2025-0002",
    documentStatus: "Approved",
    documentStage: "Completed",
  },
  {
    id: 2,
    requestorName: "Bob Johnson",
    buFu: "IT",
    extension: "9012",
    submitDate: new Date("2025-01-13"),
    approvalDate: undefined,
    urgency: "Low",
    documentType: "Report",
    documentTitle: "Document 0003",
    documentDescription: "Quarterly IT infrastructure report",
    documentNumber: "DOC-2025-0003",
    documentUrl: "",
    documentStatus: "In Review",
    documentStage: "Under Review",
  },
  {
    id: 3,
    requestorName: "Alice Williams",
    buFu: "Operations",
    extension: "3456",
    submitDate: new Date("2025-01-12"),
    approvalDate: undefined,
    urgency: "High",
    documentType: "Policy",
    documentTitle: "Document 0004",
    documentDescription: "Updated safety policy document",
    documentNumber: "DOC-2025-0004",
    documentUrl: "",
    documentStatus: "Pending",
    documentStage: "Awaiting Approval",
  },
  {
    id: 4,
    requestorName: "Charlie Brown",
    buFu: "Finance",
    extension: "7890",
    submitDate: new Date("2025-01-11"),
    approvalDate: new Date("2025-01-13"),
    urgency: "Medium",
    documentType: "Budget",
    documentTitle: "Document 0005",
    documentDescription: "Annual budget proposal for 2025",
    documentNumber: "DOC-2025-0005",
    documentUrl: "",
    documentStatus: "Approved",
    documentStage: "Completed",
  },
  {
    id: 5,
    requestorName: "Diana Prince",
    buFu: "Legal",
    extension: "2345",
    submitDate: new Date("2025-01-10"),
    approvalDate: new Date("2025-01-11"),
    urgency: "High",
    documentType: "Agreement",
    documentTitle: "Document 0006",
    documentDescription: "Vendor service agreement",
    documentNumber: "DOC-2025-0006",
    documentUrl: "",
    documentStatus: "Rejected",
    documentStage: "Rejected",
  },
  {
    id: 6,
    requestorName: "Edward Norton",
    buFu: "Marketing",
    extension: "6789",
    submitDate: new Date("2025-01-09"),
    approvalDate: undefined,
    urgency: "Low",
    documentType: "Campaign",
    documentTitle: "Document 0007",
    documentDescription: "Q1 marketing campaign proposal",
    documentNumber: "DOC-2025-0007",
    documentUrl: "",
    documentStatus: "In Review",
    documentStage: "Under Review",
  },
  {
    id: 7,
    requestorName: "Fiona Apple",
    buFu: "Sales",
    extension: "0123",
    submitDate: new Date("2025-01-08"),
    approvalDate: undefined,
    urgency: "Medium",
    documentType: "Proposal",
    documentTitle: "Document 0008",
    documentDescription: "Client proposal for enterprise account",
    documentNumber: "DOC-2025-0008",
    documentUrl: "",
    documentStatus: "Pending",
    documentStage: "Submitted",
  },
  {
    id: 8,
    requestorName: "George Lucas",
    buFu: "IT",
    extension: "4567",
    submitDate: new Date("2025-01-07"),
    approvalDate: new Date("2025-01-09"),
    urgency: "High",
    documentType: "Request",
    documentTitle: "Document 0009",
    documentDescription: "Hardware procurement request",
    documentNumber: "DOC-2025-0009",
    documentUrl: "",
    documentStatus: "Approved",
    documentStage: "Completed",
  },
  {
    id: 9,
    requestorName: "Helen Keller",
    buFu: "HR",
    extension: "8901",
    submitDate: new Date("2025-01-06"),
    approvalDate: undefined,
    urgency: "Low",
    documentType: "Policy",
    documentTitle: "Document 0010",
    documentDescription: "Remote work policy update",
    documentNumber: "DOC-2025-0010",
    documentUrl: "",
    documentStatus: "In Review",
    documentStage: "Under Review",
  },
  {
    id: 10,
    requestorName: "Isaac Newton",
    buFu: "Finance",
    extension: "2345",
    submitDate: new Date("2025-01-05"),
    approvalDate: undefined,
    urgency: "Medium",
    documentType: "Report",
    documentTitle: "Document 0011",
    documentDescription: "Financial audit report",
    documentNumber: "DOC-2025-0011",
    documentUrl: "",
    documentStatus: "Pending",
    documentStage: "Awaiting Approval",
  },
];
