import "@/app/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/shared/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import DocumentSubmissionSidebar from "./_components/document-submission-sidebar";
import Header from "@/components/shared/header/header";
import AppFooter from "@/components/shared/footer";
import { Toaster } from "@/components/ui/sonner";

type RootLayoutProps = {
  children: React.ReactNode;
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <DocumentSubmissionSidebar />
            <div className="flex flex-1 flex-col relative min-h-svh w-full max-w-full overflow-hidden">
              <Header />
              <main className="flex flex-1 mt-[100px] flex-col w-full max-w-full min-h-0">
                {children}
              </main>
              <AppFooter />
            </div>
          </SidebarProvider>
          <Toaster closeButton position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
