import {
  WarehouseIcon,
  FileTextIcon,
  ThermometerIcon,
  BanknoteArrowDownIcon,
  NotebookPenIcon,
  ShoppingCartIcon,
  AlbumIcon,
  ShipIcon,
  Package2Icon,
  CombineIcon,
  BrickWallShieldIcon,
  MonitorCloudIcon,
  HammerIcon,
  ShieldIcon,
} from "lucide-react";

export const allModules = [
  {
    id: 1,
    name: "digital_document_sub",
    title: "Digital Document Submission",
    icon: FileTextIcon,
    link: "/document-submission",
  },
  {
    id: 2,
    name: "warehouse_mgt",
    title: "Warehouse Management",
    icon: WarehouseIcon,
    link: "/warehouse-management",
  },
  {
    id: 3,
    name: "warehouse_temperature",
    title: "Warehouse Temperature",
    icon: ThermometerIcon,
    link: "/warehouse-temperature",
  },
  {
    id: 4,
    name: "expense_mgt",
    title: "Expense Management",
    icon: BanknoteArrowDownIcon,
    link: "/expense-management",
  },
  {
    id: 5,
    name: "expense_requisition",
    title: "Expense Requisition",
    icon: NotebookPenIcon,
    link: "/expense-requisition",
  },
  {
    id: 6,
    name: "purchase_mgt",
    title: "Purchase Management",
    icon: ShoppingCartIcon,
    link: "/purchase-management",
  },
  {
    id: 7,
    name: "treasury_mgt",
    title: "Treasury",
    icon: AlbumIcon,
    link: "/treasury",
  },
  {
    id: 8,
    name: "shipment_tracking",
    title: "Digital Shipment Tracking",
    icon: ShipIcon,
    link: "/shipment-tracking",
  },
  {
    id: 9,
    name: "product_registration",
    title: "Product Registration",
    icon: Package2Icon,
    link: "/product-registration",
  },
  {
    id: 10,
    name: "collection_mgt",
    title: "Collection Management",
    icon: CombineIcon,
    link: "/collection-management",
  },
  {
    id: 11,
    name: "stock_mgt",
    title: "Admin Stock Management",
    icon: BrickWallShieldIcon,
    link: "/stock-management",
  },
  {
    id: 12,
    name: "it_service_mgt",
    title: "IT Service Management",
    icon: MonitorCloudIcon,
    link: "/it-service-management",
  },
  {
    id: 13,
    name: "dynamic_tools",
    title: "Dynamic Tools",
    icon: HammerIcon,
    link: "/dynamic-tool",
  },
  {
    id: 99,
    name: "system_admin",
    title: "System Administration",
    icon: ShieldIcon,
    link: "/system-admin",
  },
];
